package de.uni_passau.fim.se2.sa.sign.interpretation;

import com.google.common.base.Preconditions;
import org.objectweb.asm.tree.analysis.Value;

import java.util.Set;

/** An enum representing the possible abstract values of the sign analysis. */
public enum SignValue implements Value {
  // Important! This implementation is kind of fragile. Don't change the order of enum values!
  // Otherwise, code will break 🤡:)
  BOTTOM("⊥"), // 0
  MINUS("{–}"), // 1
  ZERO("{0}"), // 2
  ZERO_MINUS("{0,–}"), // 3 == ZERO | MINUS
  PLUS("{+}"), // 4 == 4
  PLUS_MINUS("{+,–}"), // 5 == PLUS | MINUS
  ZERO_PLUS("{0,+}"), // 6 == ZERO | PLUS
  TOP("⊤"), // 7 == MINUS | ZERO | PLUS
  UNINITIALIZED_VALUE("∅"); // 8

  private final String repr;

  SignValue(final String pRepr) {
    repr = pRepr;
  }

  @Override
  public int getSize() {
    return 1;
  }

  @Override
  public String toString() {
    return repr;
  }

  // Below method is generated by LLM.
  // Please refer to LLM/code_queries.txt
  public SignValue join(final SignValue pOther) {
    Preconditions.checkState(
        this != UNINITIALIZED_VALUE && pOther != UNINITIALIZED_VALUE,
        "Dummy shall not be used as a value.");

    // BOTTOM joined with anything is the other value
    if (this == BOTTOM) return pOther;
    if (pOther == BOTTOM) return this;

    // TOP joined with anything is TOP
    if (this == TOP || pOther == TOP) return TOP;

    // Perform bitwise OR on ordinal values
    int joinedOrdinal = this.ordinal() | pOther.ordinal();
    return SignValue.values()[joinedOrdinal];
  }

  public boolean isLessOrEqual(final SignValue pOther) {
    Preconditions.checkState(
        this != UNINITIALIZED_VALUE && pOther != UNINITIALIZED_VALUE,
        "Dummy shall not be used as a value.");
    return this.join(pOther) == pOther;
  }

  public static boolean isZero(final SignValue pValue) {
    return pValue == ZERO;
  }

  public static boolean isMaybeZero(final SignValue pValue) {
    return pValue == ZERO || pValue == ZERO_MINUS || pValue == ZERO_PLUS || pValue == TOP;
  }

  public static boolean isNegative(final SignValue pValue) {
    return pValue == SignValue.MINUS;
  }

  public static boolean isMaybeNegative(final SignValue pValue) {
    return pValue == SignValue.MINUS || pValue == ZERO_MINUS || pValue == PLUS_MINUS || pValue == TOP;
  }

  public static Set<Sign> toSignSet(SignValue value) {
    return switch (value) {
      case BOTTOM -> throw new IllegalStateException("BOTTOM value not allowed");
      case MINUS -> Set.of(Sign.MINUS);
      case ZERO -> Set.of(Sign.ZERO);
      case ZERO_MINUS -> Set.of(Sign.ZERO, Sign.MINUS);
      case PLUS -> Set.of(Sign.PLUS);
      case PLUS_MINUS -> Set.of(Sign.PLUS, Sign.MINUS);
      case ZERO_PLUS -> Set.of(Sign.ZERO, Sign.PLUS);
      case TOP -> Set.of(Sign.PLUS, Sign.MINUS, Sign.ZERO);
      case UNINITIALIZED_VALUE -> throw new IllegalStateException("Uninitialized value not allowed.");
    };
  }

  public static SignValue fromSignSet(Set<Sign> signs) {
    if (signs.isEmpty()) return SignValue.BOTTOM;
    if (signs.equals(Set.of(Sign.MINUS))) return SignValue.MINUS;
    if (signs.equals(Set.of(Sign.ZERO))) return SignValue.ZERO;
    if (signs.equals(Set.of(Sign.ZERO, Sign.MINUS))) return SignValue.ZERO_MINUS;
    if (signs.equals(Set.of(Sign.PLUS))) return SignValue.PLUS;
    if (signs.equals(Set.of(Sign.PLUS, Sign.MINUS))) return SignValue.PLUS_MINUS;
    if (signs.equals(Set.of(Sign.ZERO, Sign.PLUS))) return SignValue.ZERO_PLUS;
    if (signs.containsAll(Set.of(Sign.MINUS, Sign.ZERO, Sign.PLUS))) return SignValue.TOP;
    if (signs.equals(Set.of(Sign.TOP))) return SignValue.TOP;
    throw new IllegalStateException("Unknown sign set: " + signs);
  }
}
